# Generated by Django 4.0.2 on 2022-02-05 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_myuser_address_myuser_contact_alter_address_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='location',
        ),
    ]
